# Generated by Django 6.0.4 on 2026-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_number', models.CharField(max_length=100)),
                ('sold_to_name', models.CharField(max_length=255)),
                ('ship_to_name', models.CharField(max_length=255)),
                ('production_block', models.CharField(max_length=100)),
                ('document_cutoff_date', models.DateField()),
            ],
        ),
    ]
