# Generated by Django 6.0.4 on 2026-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_document_cutoff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='block_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
